#name, main, version and api are required
name: MoneyBooster
main: MoneyBooster\MoneyBooster
version: 1.0.0
api: 3.0.0

load: POSTWORLD
author: Alexzvn
description: Plugin đi nạp thẻ cho member
website: https://github.com/alexzvn/moneybooster-mcpe
commands:
 napthe:
  description: Lệnh nạp thẻ
  usage: "/napthe <mệnh giá> <mã thẻ> <seri> [loại thẻ]"
  permission: moneybooster.napthe.use

permissions:
 moneybooster.napthe.use:
  description: "Cho người chơi nạp thẻ"
  default: true
